### ISSUE TITLE
Train model for generating random Pokemon names

### ISSUE THREAD

**Issue by simibac** [PokeMate/name-generator#1]
## User Story
As a user, I want to have a unique name for my newly mated Pokemon.

## Description
A model should be trained which can generate random Pokemon names efficiently. 

## Tasks
- [x] Find or generate a list of existing Pokemon names
- [x] Setup or clone a NN
- [x] Train a model
- [x] Export the model such that it can be integrated into a REST Api
