### ISSUE TITLE
Exposing the model with a RESTful Api 

### ISSUE THREAD

**Issue by simibac** [PokeMate/name-generator#2]
## User Story
As a developer, I want to have an API for generating new Pokemon names so that it can be integrated as a micro service into other application.

## Description
- The model which is generated in #1 is used to build a REST Api, which can be used to query random Pokemon from other services. 
- The Swagger integration allows for testing the endpoints quickly.
- A Dockerfile should be provided such that it can be integrated as a microservice and scaled in future.

## Tasks
- [x] Setup flask, restplus
- [x] Setup a service that uses the model from #1 to generate names
- [x] Setup REST Api with a GET-route to query a specified number of random Pokemon names
- [ ] Test the endpoint
- [ ] Test the service for using the model from #1 
- [ ] Integrate Swagger
- [ ] Setup Dockerfile
